-- ============================================================
-- LoveAndLove — Seed de frases românticas
-- Rode isso DEPOIS do supabase-schema.sql, uma única vez.
-- ============================================================

insert into frases (texto) values
('De todas as histórias que eu já vivi, essa é a minha favorita.'),
('Encontrei em você o lugar onde meu coração quis ficar.'),
('Antes de você, eu nem sabia que sentir tanto era possível.'),
('Você é o motivo dos meus melhores dias.'),
('Com você, até o silêncio é companhia boa.'),
('Cada dia ao seu lado é um capítulo que eu quero guardar.'),
('Amar você é a coisa mais fácil que eu já fiz.'),
('Você chegou e trouxe luz pra lugares que eu nem sabia que estavam escuros.'),
('Se eu pudesse escolher de novo, escolheria você mil vezes.'),
('O meu lugar favorito no mundo é ao seu lado.'),
('Você é a prova de que os melhores encontros são os inesperados.'),
('Entre todas as pessoas, o universo escolheu você pra mim.'),
('Seu abraço é o meu porto seguro.'),
('Com você aprendi que amor não precisa ser perfeito, só precisa ser verdadeiro.'),
('Você é a resposta para perguntas que eu nem sabia que tinha feito.'),
('Cada detalhe seu é o meu favorito.'),
('Ao seu lado, o tempo anda diferente — mais leve, mais bonito.'),
('Você transformou os meus dias comuns em momentos inesquecíveis.'),
('Te escolher é a decisão mais fácil que eu tomo todos os dias.'),
('Você é aquele tipo de pessoa que a gente sonha em encontrar.'),
('Nosso amor é a prova de que algumas histórias merecem ser contadas.'),
('Com você, eu aprendi o verdadeiro significado de chegar em casa.'),
('Você é o motivo do meu sorriso mais sincero.'),
('Te amar é o jeito mais bonito que encontrei de ser feliz.'),
('Cada memória com você é um tesouro que eu guardo com carinho.'),
('Você fez do meu coração um lugar mais cheio de vida.'),
('Com você, simplicidade vira poesia.'),
('Você é a razão de eu acreditar em finais felizes de verdade.'),
('O nosso amor cresce a cada dia, como se fosse a primeira vez.'),
('Você é a pessoa que eu quero ao lado em todos os capítulos da minha vida.'),
('Te encontrar foi o melhor acaso que já aconteceu comigo.'),
('Com você, cada dia parece um recomeço bom.'),
('Você é meu lugar seguro no meio do caos do mundo.'),
('Nosso amor não precisa de motivo, ele simplesmente é.'),
('Você é a pessoa que faz tudo valer a pena.'),
('Cada olhar seu me lembra por que eu escolhi ficar.'),
('Com você aprendi que amor de verdade é tranquilo, como um lar.'),
('Você é a companhia que eu não troco por nada.'),
('O nosso amor é feito de pequenos detalhes que se tornaram tudo.'),
('Você me ensinou que amar é também escolher, todos os dias.'),
('Com você, o impossível parece sempre um pouco mais perto.'),
('Você é o motivo de eu acreditar em nós dois.'),
('Cada "eu te amo" seu vale mais que mil palavras bonitas.'),
('Você é meu lugar favorito, mesmo quando estamos em lugar nenhum.'),
('Com você, aprendi que o amor certo não cansa, ele descansa.'),
('Você é a pessoa que faz qualquer dia comum virar especial.'),
('Nosso amor é simples e gigante ao mesmo tempo.'),
('Você é a certeza que eu carrego no meio de tantas dúvidas.'),
('Com você, até os problemas parecem menores.'),
('Você é o motivo de eu querer ser uma pessoa melhor.'),
('Cada gesto seu é um jeito novo de me fazer feliz.'),
('Com você, eu aprendi que amor também é sobre escolher ficar.'),
('Você é a paz que eu não sabia que estava procurando.'),
('Nosso amor não é perfeito, mas é exatamente o que eu quero.'),
('Você é a pessoa que faz meu coração sentir que está em casa.'),
('Com você, cada conversa boba se torna minha lembrança favorita.'),
('Você é o motivo de eu sorrir sem nem perceber.'),
('Nosso amor cresce nas coisas pequenas do dia a dia.'),
('Você é a pessoa que eu escolho, de novo, todos os dias.'),
('Com você, o futuro parece um lugar bom pra estar.'),
('Você é a calma que chega depois de um dia difícil.'),
('Cada plano com você é mais um motivo pra sorrir.'),
('Com você aprendi que o amor de verdade soma, nunca divide.'),
('Você é o tipo de pessoa que eu quero apresentar pro resto da minha vida.'),
('Nosso amor é feito de risadas, silêncios bons e muita cumplicidade.'),
('Você é a pessoa que transforma qualquer lugar em lar.'),
('Com você, aprendi que amor de verdade não tem pressa.'),
('Você é a surpresa boa que a vida me deu.'),
('Cada dia com você é um motivo pra agradecer.'),
('Com você, eu encontrei o significado certo da palavra "nós".'),
('Você é meu favorito em qualquer multidão.'),
('Nosso amor é a prova de que o tempo certo existe.'),
('Você é a pessoa que faz meu coração bater diferente.'),
('Com você, aprendi a amar sem medo.'),
('Você é o motivo das minhas melhores histórias.'),
('Cada detalhe nosso é um pedacinho de felicidade guardado.'),
('Com você, eu aprendi que o amor de verdade é leve.'),
('Você é a pessoa que faz tudo parecer possível.'),
('Nosso amor é simples assim: verdadeiro, todos os dias.'),
('Você é meu motivo favorito pra acreditar no amor.'),
('Com você, cada despedida vem com a certeza de um novo encontro.'),
('Você é a pessoa que faz meus dias terem mais sentido.'),
('Cada momento com você é uma página que eu quero guardar pra sempre.'),
('Com você, aprendi que amor de verdade cabe nas coisas pequenas.'),
('Você é meu lugar favorito no meio de tantos caminhos.'),
('Nosso amor é feito de escolhas certas, repetidas todos os dias.'),
('Você é a pessoa que faz eu querer ser presente, de verdade.'),
('Com você, até os dias difíceis ficam mais fáceis de atravessar.'),
('Você é o motivo do meu coração estar em paz.'),
('Cada gesto de carinho seu vale mais que qualquer palavra.'),
('Com você, aprendi que o amor de verdade constrói, não destrói.'),
('Você é a pessoa que faz minha vida ter mais cor.'),
('Nosso amor é daqueles que a gente quer contar pros filhos um dia.'),
('Você é meu motivo de orgulho em cada conquista nossa.'),
('Com você, cada "para sempre" parece possível de verdade.'),
('Você é a pessoa que faz meu coração sentir gratidão todos os dias.'),
('Cada manhã ao seu lado é um recomeço bonito.'),
('Com você, aprendi que amar é também sobre crescer junto.'),
('Você é a pessoa certa, no tempo certo, do jeito certo.'),
('Nosso amor é a prova viva de que vale a pena esperar pelo certo.');
